### ISSUE TITLE
Do you have any other ch3 s3 or ch3 s4 mappings?

### ISSUE THREAD

**Issue by max8447** [Lodgical1/Fortnite-Mapping-Versions-Chapter-3-to-4#1]

**Comment by Lodgical1** [comment]
No these are the current mappings plus platform doesn't matter it's all the same game

**Comment by Lodgical1** [comment]
Although, I do plan to catch up so thank you for opening an issue otherwise I would have forgotten about the repo.

**Comment by Lodgical1** [comment]
> _No description provided._

I have changed my mind, I will add Chapter 3 to 4 versions of Fortnite

**Comment by max8447** [comment]
23.00 mapping is here: https://fnbuilds.pages.dev/builds/++Fortnite+Release-23.00-CL-23281232-Android_oo.usmap
and i have 19.00 mapping on my pc (had to upload to drive cuz github doesnt support file type): https://drive.google.com/file/d/1YncPwJdBq0fQZJgVgPXW5mFsPrW_ureq/view?usp=sharing

**Comment by Lodgical1** [comment]
OMG Thank You SOOO Much I've been needing this mapping I'll be sure to give you credit as well

**Comment by Lodgical1** [comment]
> 23.00 mapping is here: https://fnbuilds.pages.dev/builds/++Fortnite+Release-23.00-CL-23281232-Android_oo.usmap and i have 19.00 mapping on my pc (had to upload to drive cuz github doesnt support file type): https://drive.google.com/file/d/1YncPwJdBq0fQZJgVgPXW5mFsPrW_ureq/view?usp=sharing

Also I've been needing to add that version mainly cause a spent 2 hours getting all the mappings and keeping them in their respective season.

**Comment by Lodgical1** [comment]
This issue will now be Closed

**Comment by max8447** [comment]
here's the 21.20 mapping: https://drive.google.com/file/d/1wAOUKetJ0N21D6MltwwQJ2B8p6KMgrog/view?usp=sharing

**Comment by Lodgical1** [comment]
Thanks
